=== AndyBlair0/gymexperience/servicios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gymxperience">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clase" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="actividad" type="xs:string"/>
                            <xs:element name="monitor" type="xs:string"/>
                            <xs:element name="hora" type="xs:string"/>
                            <xs:element name="sala" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AndyBlair0/gymexperience/servicios.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo-datos.css"?>
<gymxperience xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="servicios.xsd">
    <clase id="C01">
        <actividad>Crossfit</actividad>
        <monitor>Abril Cantero</monitor>
        <hora>09:00</hora>
        <sala>Principal</sala>
    </clase>
    <clase id="C02">
        <actividad>Spinning</actividad>
        <monitor>Laura Pianres</monitor>
        <hora>11:30</hora>
        <sala>Sala Ciclo</sala>
    </clase>
    <clase id="C03">
        <actividad>Boxeo</actividad>
        <monitor>Dani Pedrosa</monitor>
        <hora>18:00</hora>
        <sala>Zona Sacos</sala>
    </clase>
    <clase id="C04">
        <actividad>Yoga</actividad>
        <monitor>Sara Chen</monitor>
        <hora>20:00</hora>
        <sala>Sala Multi/sala>
    </clase>
        <clase id="C05">
        <actividad>Cossfit</actividad>
        <monitor>Kiko Jimenez</monitor>
        <hora>08:00</hora>
        <sala>Principal/sala>
    </clase>

</gymxperience>
